server:
  port: 8080

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 2080
    url: jdbc:mysql://localhost:3306/department_details?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Welcome to my Spring app!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 2080
    url: jdbc:mysql://localhost:3306/department_details?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Welcome to my Spring app!!

---


spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 2080
    url: jdbc:mysql://localhost:3306/department_details?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Welcome to my Spring app!!



